# -*- auto-fill-function: nil; eval: (add-hook 'after-save-hook 'org-babel-tangle nil t); -*-

----------------------------------------------------------------------
NEXT: Reorganize branch dev and rebase it onto master.
Create copy README-dev.org of its counterpart at the tip of dev.
Create a branch goal at dev.
Reset dev hard to master.
List all changes in README-dev.org.
Gradually add them to dev.
----------------------------------------------------------------------


Create repositories on Github from inside Emacs.

* Usage
- Add ~ma-github.el~ to your Emacs load path
- Create a personal access token from Github at https://github.com/settings/tokens/new
- Set the environment variable MA_GITHUB_TOKEN with your new token
- Set the environment variable MA_GITHUB_USER with your Github user
  Then run ~M-x ma-github-create~ in Emacs, which will:
  - create the repository in github.com
  - create a folder for the local repository, and ~git init~ it
  - create a blank README file inside this folder and ~git add~ it
  - do the first commit, with the message 'Initial commit'
  - ~git push -u origin master~ it to the newly created github repo
- Set ma-github-username


* All the Code in Literate Programming
It was made using Babel, from the Org Mode in Emacs.

** This is the core function, used to create the repository.

~<<Function to create the repository>> +≡~

#+begin_src elisp :noweb-ref Function to create the repository
(defun ma-github-create (name &optional dir token kickstart git-push private)
  "Create repository NAME on Github.

Use the access token TOKEN to connect to the Github API.  If KICKSTART
is non-nil, create a blank file inside directory DIR, “Git-add” it,
then run “Git-commit”.  If GIT-PUSH is non-nil, run “Git-push” inside
DIR.  If PRIVATE is non-nil, the repository will be created “public,”
otherwise it will be created “private”."
  <<Asks for arguments when run interactively ma-github-create>>
  <<Run initial hooks>>
  <<Update "last repository" variables>>
  <<Prepare the progress report>>
    <<Create the remote repository>>
    <<Maybe create, kickstart, and/or push local repository>>
  <<Run final hooks>>)
#+end_src

The remote repository is created with an external call to =curl=.
The =curl= command (without escaping characters) has this form.

#+begin_src shell
curl -H "Authorization: token TOKEN"
    https://api.github.com/user/repos
    -d '{"name":"NAME",
         "private":PRIVATE}'
#+end_src

We need an access token.
It will be obtained from a file set in the variable ~authinfo-file~, that defaults to  =~/.authinfo.gpg=.
We'll use =auth-source.el= for that.

~<<require's>> +≡~

#+begin_src elisp :noweb-ref require's
(require 'auth-source)
#+end_src

The lines of =~/.authinfo.gpg= have the following form.

#+begin_example
machine GITHUB_API_URL login USERNAME password TOKEN
#+end_example

Let's make sure we get all three.
This has to be done in two steps, because we'll use ~let*~ to be able to access the value of the url /and/ username to fetch the token.
~let*~ first do the attributions, and then allows us to use them.
Finally, if we /did/ get all three, we call =curl= to create the remote repository.

~<<Create the remote repository>> +≡~

#+begin_src elisp :noweb-ref Create the remote repository
(let* (
       <<Do our best to get all three>>
       )
  <<Ensure we got all three>>
  <<Call curl to create the remote repository>>
  )
#+end_src

The first thing we ensure we have is the Github API URL.
Let's create a variable for that.

~<<Customization Group and Variables>> +≡~

#+begin_src elisp :noweb-ref Customization Group and Variables
(defcustom ma-github-api-url "api.github.com"
  "Github API URL."
  :type 'string
  :group 'ma-github)
#+end_src

Now let's make sure we get one.

First we set it.

~<<Do our best to get all three>> +≡~

#+begin_src elisp :noweb-ref Do our best to get all three
(api-url
 (if (string-blank-p ma-github-api-url)
     (read-string "API URL: ")
   ma-github-api-url))
#+end_src

Then test it.

~<<Ensure we got all three>> +≡~

#+begin_src elisp :noweb-ref Ensure we got all three
(if (string-blank-p api-url)
    (error "API URL cannot be empty")
  api-url)
#+end_src

Now the variable for the username, try to get it and test.

~<<Customization Group and Variables>> +≡~

#+begin_src elisp :noweb-ref Customization Group and Variables
(defcustom ma-github-username ""
  "Github username."
  :type 'string
  :group 'ma-github)
#+end_src

~<<Do our best to get all three>> +≡~

#+begin_src elisp :noweb-ref Do our best to get all three
(username
 (if (string-blank-p ma-github-username)
     (read-string "username: ")
   ma-github-username))
#+end_src

~<<Ensure we got all three>> +≡~

#+begin_src elisp :noweb-ref Ensure we got all three
(if (string-blank-p username)
    (error "username cannot be empty"))
#+end_src

Finally the token.
We won't be using variables for it for security reasons.
Let's first try and fetch it.

~<<Do our best to get all three>> +≡~

#+begin_src elisp :noweb-ref Do our best to get all three
(token
 (let ((entry (car (auth-source-search
                    :host api-url
                    :user username
                    :max 1))))
   (when entry
     (let ((token (plist-get entry :secret)))
       (if (functionp token) (funcall token) token)))))
#+end_src

Then we see if we were able to fetch the access token.

~<<Ensure we got all three>> +≡~

#+begin_src elisp :noweb-ref Ensure we got all three
(if (string-blank-p token)
  (error "token cannot be empty"))
#+end_src

If we got everything we needed, we finally call =curl=.

~<<Call curl to create the remote repository>> +≡~

#+begin_src elisp :noweb-ref Call curl to create the remote repository
(shell-command
 (concat
  "curl "
  (concat "-H \"Authorization: token " token "\" ")
  ma-github-url " "
  (concat "-d '{\"name\":\"" name "\", "
          "\"private\": "
          (if (yes-or-no-p "public?") "false" "true" ) "}'")))
#+end_src

Those three parameters are required:
- ~TOKEN~: Github API auth token;
- ~NAME~: The name of the repository;
- ~PRIVATE_FLAG~: Boolean variable controlling if the repository will be private.

~<<Asks for arguments when run interactively ma-github-create>> +≡~

#+begin_src elisp :noweb-ref Asks for arguments when run interactively ma-github-create
(interactive
 (nconc (ma-github-ask-repo-info)
        (list
         (getenv ma-github-env-token)
         (yes-or-no-p "Initial commit? ")
         (yes-or-no-p "Push to Github? ")
         (not (yes-or-no-p "Public? ")))))
#+end_src

~<<Run initial hooks>> +≡~

#+begin_src elisp :noweb-ref Run initial hooks
(run-hooks 'ma-github-create-before-start-hook)
#+end_src

~<<Run final hooks>> +≡~

#+begin_src elisp :noweb-ref Run final hooks
(run-hooks 'ma-github-create-finalize-hook)
#+end_src

~<<Update "last repository" variables>> +≡~

#+begin_src elisp :noweb-ref Update "last repository" variables
(setq ma-github-last-repo-name name)
(setq ma-github-last-repo-dir dir)
#+end_src

Let's now focus on the /local/ repository.

~<<Maybe create, kickstart, and/or push local repository>> +≡~

#+begin_src elisp :noweb-ref Maybe create, kickstart, and/or push local repository
(when dir
  <<Create, kickstart, and/or push local repository>>)
#+end_src

~<<Create, kickstart, and/or push local repository>> +≡~

#+begin_src elisp :noweb-ref Create, kickstart, and/or push local repository
(ma-github-local-create name dir)
(progress-reporter-update progress-reporter 2)

(ma-github-local-add-remote name dir)
(progress-reporter-update progress-reporter 3)

(when kickstart (ma-github-local-kickstart dir))
(progress-reporter-update progress-reporter 4)

(when git-push (ma-github-local-push dir))
(progress-reporter-done progress-reporter))
#+end_src

~<<Prepare the progress report>> +≡~

#+begin_src elisp :noweb-ref Prepare the progress report
(let ((progress-reporter
       (make-progress-reporter "Creating repository..." 0 5)))
  (progress-reporter-update progress-reporter 0)
#+end_src

** Main code structure

[[file:~/elisp/ma-github/ma-github.el][~/elisp/ma-github/ma-github.el]] ≡

#+begin_src elisp :tangle ma-github.el
<<Housekeeping: Customization, Variables, and Hooks>>

(defun ma-github-repo-ask-name ()
  "Ask for repository’s name."
  (read-string "Repository name: "))

(defun ma-github-github-ask-token ()
  "Ask for the Github access token."
  (let ((input (read-string
                (concat "Github access token (default "
                        ma-github-env-token "): "))))
    (if (string= "" input)
        (getenv ma-github-env-token)
      input)))

(defun ma-github-local-ask-path (name)
  "Ask for local repository’s path, with NAME as the default dir."
  (expand-file-name
   (read-directory-name "Repository dir: " name)))

(defun ma-github-ask-repo-info ()
  "Ask for repository’s name and local path."
  (let ((name (read-string "Repository name: ")))
    ;; Create a list to return with repository's name and dir
    (list name (ma-github-local-ask-path name))))

(defun ma-github-local-add-remote (name dir)
  "Add a “Git remote” for repository called NAME inside directory DIR."
  (shell-command
   (concat "git -C " dir " remote add origin "
           "git@github.com:"
           (getenv ma-github-env-user) "/"
           name ".git")))

(defun ma-github-local-create (name dir)
  "Create a new local repository called NAME inside directory DIR."
  (interactive (ma-github-ask-repo-info))
  (ignore-errors (make-directory dir t))
  (shell-command (concat "git -C " dir " init .")))

(defun ma-github-local-kickstart (dir)
  "Create a blank file inside DIR, “Git-add” it, then run “Git-commit”."
  (interactive "DRepository dir: ")
  (shell-command (concat "touch " dir "/README"))
  (shell-command (concat "git -C " dir " add " dir "/README"))
  (shell-command (concat "git -C " dir " commit -m 'Initial commit'")))

(defun ma-github-local-push (dir)
  "Run “Git-push” on the repository inside directory DIR."
  (shell-command
   (concat "git -C " dir " push -u origin master")))

<<Function to create the repository>>
#+end_src

** This allows for the facilities under ~M-x customize-group RET ma-github~.
~<<Customization Group and Variables>> +≡~

#+begin_src elisp :noweb-ref Customization Group and Variables
(defgroup ma-github nil
  "Interact with Github.")

(defcustom ma-github-url "https://api.github.com/user/repos"
  "URL address used to create a new repository."
  :type 'string
  :group 'ma-github)

(defcustom ma-github-env-token "MA_GITHUB_TOKEN"
  "Environment variable containing the access token."
  :type 'string
  :group 'ma-github)

(defcustom ma-github-env-user "MA_GITHUB_USER"
  "Environment variable containing the username."
  :type 'string
  :group 'ma-github)
#+end_src

** Variables
~<<Variables>> +≡~

#+begin_src elisp :noweb-ref Variables
(defvar ma-github-last-repo-name nil
  "Name of the last repository created.")

(defvar ma-github-last-repo-dir nil
  "Directory of the last repository created.")
#+end_src

** Hooks
~<<Hooks>> +≡~

#+begin_src elisp :noweb-ref Hooks
(defvar ma-github-create-before-start-hook nil
  "Hook run at the start of ‘ma-github-create’.")

(defvar ma-github-create-finalize-hook nil
  "Hook run at the end of ‘ma-github-create’.")
#+end_src

** Housekeeping
~<<Housekeeping: Customization, Variables, and Hooks>> +≡~

#+begin_src elisp :noweb-ref Housekeeping: Customization, Variables, and Hooks
<<require's>>
<<Customization Group and Variables>>

<<Variables>>

<<Hooks>>
#+end_src
